language: node_js
node_js:
    - "6"
cache:
  directories:
    - "node_modules"

install: npm install
script:
    - npm run build
    - mkdir local_dir
    - mv index.html local_dir/
    - mv style/ local_dir/
    - mv script/ local_dir/
    - rm -rf local_dir/script/es2015

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  local_dir: local_dir
  on:
    branch: master
  name: mapan1984
  email: mapan1984@outlook.com

